# Site settings
title: Tachibana Online
SEOTitle: Tata的空间 | Tachibana Online
header-img: img/home-bg.jpg
email: wjh1429079043@outlook.com
description: "这里是 @Tachibana 的个人空间，与你一起发现更大的世界 |反正在学校都是牛马"
keyword: "阿伟, 韦景皓, Tachibana, 东辰, 绵阳东辰学校, 东辰高中, 阿伟的空间, Tachibana Online, 空间, 个人网站, 互联网, Web, JavaScript, React, React Native, "
url: "https://tachibana-kousuke.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: Tachibana
zhihu_username: Tachibana
github_username: Tachibana
twitter_username: Tachibana
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: Tachibana

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: tachibana-kousuke.github.io

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "反正在学校都是牛马 <br> 我也不知道该说什么"
sidebar-avatar: https://github.com/Huxpro.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "赵烽皓howcam，他的GitHub项目提供了学习资料", href: "http://howcam.github.io" },
  ]
